package com.monmouthvalley.tandoor.shared;

public enum Category {
    APPETIZER,
    SOUP,
    TANDOOR_BREAD,
    TANDOORI_SPECIALTY,
    CHICKEN_SPECIALTY,
    LAMB_SPECIALTY,
    SEAFOOD_SPECIALTY,
    VEGETARIAN_SPECIALTY,
    RICE_SPECIALTY,
    DOSAI,
    UTHAPAM,
    NORTH_INDIAN_THALI,
    ACCOMPANIMENT,
    DESSERT,
    BEVERAGE,
}
