#image: java:8

stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw clean package
  artifacts:
    paths:
      - target/tandoor-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:

  only:
    - master
